# Generated by Django 4.0.6 on 2022-07-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
